name: Setup
description: Setup node, yarn and install dependencies

inputs:
  node-version:
    description: Version of Node to use
    default: 16.x

runs:
  using: composite
  steps:
    - name: 🏗 Setup Node
      uses: actions/setup-node@v3.4.1
      with:
        node-version: ${{ inputs.node-version }}
        cache: yarn

    - name: 🏗 Find yarn cache
      uses: actions/cache@v3.0.5
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: yarn-cache-folder-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
        restore-keys: |
          yarn-cache-folder-

    - name: 📦 Install dependencies
      run: yarn install --immutable
      shell: bash
