name: Setup
description: Setup nx, node, yarn and install dependencies

inputs:
  node-version:
    description: Version of Node to use
    default: 18.x

runs:
  using: composite
  steps:
    - uses: nrwl/nx-set-shas@v3

    - name: 🏗 Setup Node
      uses: actions/setup-node@v3.4.1
      with:
        node-version: ${{ inputs.node-version }}
        cache: yarn

    - name: 🏗 Find yarn cache
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      shell: bash

    # https://github.com/actions/cache
    - name: 🏗 Restore Yarn cache
      uses: actions/cache@v3.0.5
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: yarn-cache-folder-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
        restore-keys: |
          yarn-cache-folder-

    - name: 📦 Install dependencies
      run: yarn install --immutable
      shell: bash
